# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46d7218638da04978a38b1e44a3d2f47e03872a309758e474467fe9fe38435a586f3f99b2e13351ade2d58dabff0b5b6ba87bb91c4aee7b17caceb78f5cbc579

test:
  secret_key_base: 2ae8ad45bb83a7648419fe4e9958e049da178ed45132ae908cbc857e9a65ebff82846d6a45a1f454be1ae022827da251dfd9673e26be5f156e34314afdf7cbde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
