# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0368d380495fa3c38da2298ea4168a2eac2f0ff83a2958199437a2d58d816fc8b6323c2cdc9389bfc51831312d474a094eade304333ada54a1b76392c19b11e3

test:
  secret_key_base: 61556ec2d2fb53b2de6b8f0e0b534ffbaee6dd0a733f3b08d2e77d2bdc8f33f3924f303820ded7184a18a36469a172ddf1ce836b2fec586d9d0d6082ff325c6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
